package hello;

import org.mariuszgromada.math.mxparser.Expression;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	@GetMapping("/")
	public String home() {
		return "<!DOCTYPE html>"
				+ "<html>"
				+ "<head>"
				+ "<title>Calculator</title>"
				+ "<style>"
				+ "body {"
				+ "   font-family: Arial, sans-serif;"
				+ "   background-color: #f0f0f0;"
				+ "   display: flex;"
				+ "   justify-content: center;"
				+ "   align-items: center;"
				+ "   height: 100vh;"
				+ "   margin: 0;"
				+ "}"
				+ "h1 {"
				+ "   text-align: center;"
				+ "   color: #333;"
				+ "   margin-bottom: 20px;"
				+ "}"
				+ ".container {"
				+ "   background-color: #fff;"
				+ "   padding: 30px;"
				+ "   border-radius: 10px;"
				+ "   box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);"
				+ "   max-width: 400px;"
				+ "   width: 100%;"
				+ "   text-align: center;"
				+ "}"
				+ "input[type='text'] {"
				+ "   width: calc(100% - 20px);"
				+ "   padding: 10px;"
				+ "   margin-top: 10px;"
				+ "   border: 1px solid #ccc;"
				+ "   border-radius: 5px;"
				+ "}"
				+ "input[type='submit'] {"
				+ "   background-color: #4CAF50;"
				+ "   color: white;"
				+ "   padding: 10px 20px;"
				+ "   margin-top: 20px;"
				+ "   border: none;"
				+ "   border-radius: 5px;"
				+ "   cursor: pointer;"
				+ "   width: 100%;"
				+ "}"
				+ "input[type='submit']:hover {"
				+ "   background-color: #45a049;"
				+ "}"
				+ "</style>"
				+ "</head>"
				+ "<body>"
				+ "<div class='container'>"
				+ "<h1>Calculator</h1>"
				+ "<form action='/calculate' method='GET'>"
				+ "<label for='expression'>Enter example:</label><br>"
				+ "<input type='text' id='expression' name='expression'><br><br>"
				+ "<input type='submit' value='Calculate'>"
				+ "</form>"
				+ "</div>"
				+ "</body>"
				+ "</html>";
	}

	@GetMapping("/calculate")
	public String calculate(@RequestParam(value = "expression") String expression) {

		Expression exp = new Expression(expression);
		double result = exp.calculate();

		if (Double.isNaN(result)) {
			return "<!DOCTYPE html>"
					+ "<html>"
					+ "<head>"
					+ "<title>Error!</title>"
					+ "<style>"
					+ "body {"
					+ "   font-family: Arial, sans-serif;"
					+ "   background-color: #f0f0f0;"
					+ "   display: flex;"
					+ "   justify-content: center;"
					+ "   align-items: center;"
					+ "   height: 100vh;"
					+ "   margin: 0;"
					+ "} "
					+ ".container {"
					+ "   background-color: #fff;"
					+ "   padding: 30px;"
					+ "   border-radius: 10px;"
					+ "   box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);"
					+ "   max-width: 400px;"
					+ "   width: 100%;"
					+ "   text-align: center;"
					+ "} "
					+ "h1 {"
					+ "   color: red;"
					+ "} "
					+ "a {"
					+ "   text-decoration: none;"
					+ "   color: white;"
					+ "   background-color: #4CAF50;"
					+ "   padding: 10px 20px;"
					+ "   border-radius: 5px;"
					+ "   display: inline-block;"
					+ "} "
					+ "a:hover {"
					+ "   background-color: #45a049;"
					+ "} "
					+ "</style>"
					+ "</head>"
					+ "<body>"
					+ "<div class='container'>"
					+ "<h1>Error!</h1>"
					+ "<a href='/'>Back</a>"
					+ "</div>"
					+ "</body>"
					+ "</html>";
		}

		return "<!DOCTYPE html>"
				+ "<html>"
				+ "<head>"
				+ "<title>Результат</title>"
				+ "<style>"
				+ "body {"
				+ "   font-family: Arial, sans-serif;"
				+ "   background-color: #f0f0f0;"
				+ "   display: flex;"
				+ "   justify-content: center;"
				+ "   align-items: center;"
				+ "   height: 100vh;"
				+ "   margin: 0;"
				+ "} "
				+ ".container {"
				+ "   background-color: #fff;"
				+ "   padding: 30px;"
				+ "   border-radius: 10px;"
				+ "   box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);"
				+ "   max-width: 400px;"
				+ "   width: 100%;"
				+ "   text-align: center;"
				+ "} "
				+ "h1 {"
				+ "   color: #333;"
				+ "} "
				+ "a {"
				+ "   text-decoration: none;"
				+ "   color: white;"
				+ "   background-color: #4CAF50;"
				+ "   padding: 10px 20px;"
				+ "   border-radius: 5px;"
				+ "   display: inline-block;"
				+ "} "
				+ "a:hover {"
				+ "   background-color: #45a049;"
				+ "} "
				+ "</style>"
				+ "</head>"
				+ "<body>"
				+ "<div class='container'>"
				+ "<h1>Result: " + result + "</h1>"
				+ "<a href='/'>Back</a>"
				+ "</div>"
				+ "</body>"
				+ "</html>";
	}
}